version: "3.8"
services:
  redis:
    image: redis:6.0
    restart: always
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    restart: always
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  redis:
    driver: local