version: '3.8'
services:
  bookshop-api:
    container_name: bookshop
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - redis-commander
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgressql/data
  
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
    volumes:
      driver: local

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  postgres:
    name: bookshop
  redis:
    driver: local